# Generated by Django 5.0 on 2023-12-07 17:42

import records.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humidity', models.IntegerField(validators=[records.validators.validate_humidity])),
                ('temperature', models.IntegerField(validators=[records.validators.validate_temperature])),
                ('wind', models.IntegerField(validators=[records.validators.validate_wind])),
                ('date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('condition', models.CharField(choices=[('1', 'Sunny weather'), ('2', 'Cloudy weather'), ('3', 'Rainy weather'), ('4', 'Flurry weather')], default='1', max_length=1)),
            ],
        ),
    ]
